<?php
$row1Images = $block->getGalleryImages(1);
$row2Images = $block->getGalleryImages(2);
$row1Count = $row1Images->getSize();
$row2Count = $row2Images->getSize();

$helper = $this->helper('Lof\LazyLoad\Helper\Data');
$loadingIcon = $helper->getConfig('general/loadingIcon');
$imgSrc = $helper->getMediaUrl().'lof'.DIRECTORY_SEPARATOR.'lazyload'.DIRECTORY_SEPARATOR.$loadingIcon;
?>
<?php if($row1Count || $row2Count): ?>
<div class="grid-container">
    <?php if($row1Count): ?>
        <div class="grid12-12 row1">
            <?php foreach($row1Images as $image): ?>
                <div class="tile-image <?php echo $image->getClass()?>">
                    <a href="<?php echo $image->getLink()?>">
                        <div class="ban <?php echo $image->getEffect()?>">
                            <img class="lof-lazy image"
                                 src="<?php echo $imgSrc ?>"
                                 title="<?php echo $image->getTitle()?>"
                                 alt="<?php echo $image->getTitle()?>"
                                 data-src="<?php echo $block->getMediaUrl($image->getImageDesktop())?>"
                            />
                        </div>
                    </a>
                </div>
            <?php endforeach;?>
        </div>
    <?php endif;?>
    <?php if($row2Count): ?>
        <div class="grid12-12 row2">
            <?php foreach($row2Images as $image): ?>
                <div class="tile-image <?php echo $image->getClass()?>">
                    <a href="<?php echo $image->getLink()?>">
                        <div class="ban <?php echo $image->getEffect()?>">
                            <img class="lof-lazy image"
                                 src="<?php echo $imgSrc ?>"
                                 title="<?php echo $image->getTitle()?>"
                                 alt="<?php echo $image->getTitle()?>"
                                 data-src="<?php echo $block->getMediaUrl($image->getImageDesktop())?>"
                            />
                        </div>
                    </a>
                </div>
            <?php endforeach;?>
        </div>
    <?php endif;?>

</div>
<?php endif;?>